name: docdoc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-271.0.dev


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # code generation (mainly used with cubit & retrofit)
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

  # Dependency injection
  get_it: ^9.2.0

  # Automatically generate code for converting to and from JSON
  json_serializable: ^6.11.3
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.9.0
  retrofit: ^4.9.1
  retrofit_generator: ^10.2.1
  pretty_dio_logger: ^1.4.0

  # Localization
  intl: ^0.20.2
  easy_localization: ^3.0.8

  # Splash Screen
  flutter_native_splash: ^2.4.7

  # screen responsive
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - images/a_dot_burr.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

